baseurl       = "https://blog.bswiecki.dev/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title         = "Just a dev blog"
canonifyurls  = true
enableEmoji = true

DefaultContentLanguage = "en"
theme                  = "beautifulhugo"
metaDataFormat         = "yaml"
pygmentsUseClasses     = true
pygmentCodeFences      = true
disqusShortname       = "blogbswieckidev"

[Params]
  subtitle      = "A brain-dump-like blog"
  dateFormat    = "January 2, 2006"
  commit        = false
  rss           = true
  comments      = true

[Author]
  name = "Bartłomiej Święcki"
  github = "byo"
  linkedin = "bswiecki"
  keybase = "byo"


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
